package me.data_architect.m2mm.data

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class LocalLlmService(private val context: Context) : LlmService {

    override suspend fun generateEncouragementDynamic(gameContext: GameContext): Result<LlmResult> = withContext(Dispatchers.IO) {
        try {
            android.util.Log.d("LocalLlmService", "Starting local AICore call...")
            
            val systemInstructionText = """
                Tu es le Primarque ${gameContext.primarchName} de la légion ${gameContext.legionName}.
                Tu es un coach de motivation personnel impitoyable mais juste, inspirant et charismatique.
                Ton objectif est d'encourager le joueur.
                
                RÈGLES ABSOLUES :
                1. TU DOIS RÉPONDRE EXCLUSIVEMENT AU FORMAT JSON.
                2. LE JSON DOIT CONTENIR EXACTEMENT DEUX CLÉS : 'reasoning' (pour tes réflexions) et 'answer' (pour la phrase finale).
                3. TA PHRASE DANS 'answer' DOIT ÊTRE UNE SEULE ET UNIQUE PHRASE, COURTE POUR RENTRER DANS UNE NOTIFICATION PUSH ANDROID.
            """.trimIndent()
            
            val promptText = """
                Contexte du joueur :
                - Niveau Actuel : ${gameContext.currentLevel} (Score: ${gameContext.currentScore}/${gameContext.currentScore + gameContext.pointsToNextLevel})
                - Tendance sur 7 jours : de ${gameContext.score7DaysAgo} à ${gameContext.currentScore}
                - Activités Récentes (Faites) : ${gameContext.recentActivitiesDone.joinToString(", ")}
                - Activités Manquées (Malus) : ${gameContext.recentActivitiesMissed.joinToString(", ")}
                - Activités Possibles : ${gameContext.allAvailableActivities.joinToString(", ")}
                
                Génère un message d'encouragement dynamique.
            """.trimIndent()

            val combinedPrompt = systemInstructionText + "\n\n" + promptText

            // =========================================================
            // IMPLÉMENTATION RÉELLE AICORE
            // =========================================================
            android.util.Log.d("LocalLlmService", "Initialisation du modèle local...")
            // 1. Initialiser le GenerativeModel d'AICore avec GenerationConfig
            val config = com.google.ai.edge.aicore.GenerationConfig.Builder().apply {
                context = this@LocalLlmService.context
            }.build()
            
            val model = com.google.ai.edge.aicore.GenerativeModel(config)
            
            // 2. Lancer l'inférence (suspend function)
            android.util.Log.d("LocalLlmService", "Génération du contenu...")
            val result = model.generateContent(combinedPrompt)
            val realResponse = result.text ?: ""
            
            android.util.Log.d("LocalLlmService", "Réponse brute AICore: ${realResponse}")

            // 4. Parse the internal JSON generated by the LLM
            // Remove potential markdown code blocks around JSON if the LLM adds them
            val cleanText = realResponse.replace(Regex("```json\\s*", RegexOption.IGNORE_CASE), "")
                                .replace(Regex("```\\s*"), "")
                                .trim()

            val parsedJson = org.json.JSONObject(cleanText)
            val finalAnswer = parsedJson.optString("answer", "Erreur de parsing local.")
            val reasoning = parsedJson.optString("reasoning", "")
            
            val formattedResponse = if (reasoning.isNotEmpty()) {
                "🤔 Réflexion du LLM :\n$reasoning\n\n🎯 Réponse finale :\n$finalAnswer"
            } else {
                finalAnswer
            }

            Result.success(LlmResult(prompt = combinedPrompt, response = formattedResponse))
            
        } catch (e: Exception) {
            e.printStackTrace()
            Result.failure(e)
        }
    }
}
