package me.data_architect.m2mm.data

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class LocalLlmService(private val context: Context) : LlmService {

    override suspend fun generateEncouragementDynamic(gameContext: GameContext): Result<LlmResult> = withContext(Dispatchers.IO) {
        try {
            android.util.Log.d("LocalLlmService", "Starting local AICore call...")
            
            val prompts = buildLlmPrompts(gameContext)
            val combinedPrompt = prompts.first + "\n\n" + prompts.second

            android.util.Log.d("LocalLlmService", "Sending combined prompt:\n$combinedPrompt")

            // =========================================================
            // IMPLÉMENTATION RÉELLE AICORE
            // =========================================================
            android.util.Log.d("LocalLlmService", "Initialisation du modèle local...")
            // 1. Initialiser le GenerativeModel d'AICore avec GenerationConfig
            val config = com.google.ai.edge.aicore.GenerationConfig.Builder().apply {
                context = this@LocalLlmService.context
            }.build()
            
            val model = com.google.ai.edge.aicore.GenerativeModel(config)
            
            // 2. Lancer l'inférence (suspend function)
            android.util.Log.d("LocalLlmService", "Génération du contenu...")
            val result = model.generateContent(combinedPrompt)
            val realResponse = result.text ?: ""
            
            android.util.Log.d("LocalLlmService", "Réponse brute AICore:\n${realResponse}")

            // 4. Parse the internal JSON generated by the LLM
            // Remove potential markdown code blocks around JSON if the LLM adds them
            val cleanText = realResponse.replace(Regex("```json\\s*", RegexOption.IGNORE_CASE), "")
                                .replace(Regex("```\\s*"), "")
                                .trim()

            val parsedJson = org.json.JSONObject(cleanText)
            val finalAnswer = parsedJson.optString("answer", "Erreur de parsing local.")
            val reasoning = parsedJson.optString("reasoning", "")
            
            val formattedResponse = if (reasoning.isNotEmpty()) {
                "🤔 Réflexion du LLM :\n$reasoning\n\n🎯 Réponse finale :\n$finalAnswer"
            } else {
                finalAnswer
            }

            Result.success(LlmResult(prompt = combinedPrompt, response = formattedResponse))
            
        } catch (e: Exception) {
            android.util.Log.e("LocalLlmService", "Exception during Local LLM inference: ${e.message}", e)
            e.printStackTrace()
            Result.failure(e)
        }
    }
}
